FROM golang:1.24-bookworm AS build

RUN CGO_ENABLED=0 go install github.com/minio/minio@RELEASE.2025-10-15T17-29-55Z

FROM debian:bookworm-slim

COPY --from=build /go/bin/minio /usr/local/bin/minio
RUN useradd --system --uid 10001 --create-home minio \
  && mkdir -p /data \
  && chown minio:minio /data
USER minio
EXPOSE 9000 9001
ENTRYPOINT ["minio"]
CMD ["server", "/data", "--console-address", ":9001"]
